### ISSUE TITLE
Doc is wrong about the constructor

### ISSUE THREAD

**Issue by Fale** [auraphp/Aura.SqlSchema#4]
The doc affirms:

```
$schema = new MysqlSchema($pdo);
```

while in the source the __constructor is:

```
public function __construct(PDO $pdo, ColumnFactory $column_factory)
```

so it will always be an error, since no ColumnFactory is provided.
The error is:

```
PHP Catchable fatal error:  Argument 2 passed to Aura\Sql_Schema\AbstractSchema::__construct() must be an instance of Aura\Sql_Schema\ColumnFactory, none given, called in /home/fale/sql2md/src/sql2json.php on line 17 and defined in /home/fale/sql2md/vendor/aura/sql-schema/src/AbstractSchema.php on line 69
```

**Comment by harikt** [comment]
Hey @Fale , 

Thank you for informing about the problem. Will you be able to open a patch to the docs ?

**Comment by Fale** [comment]
Does it expects an new one or it has to contain something?

**Comment by harikt** [comment]
It expects a ColumnFactory object as second param. See https://github.com/auraphp/Aura.Sql_Schema/blob/develop-2/src/AbstractSchema.php#L69

So the real way is 

``` php
$query_factory = new Aura\Sql_Schema\ColumnFactory();
$schema = new Aura\Sql_Schema\MysqlSchema($pdo, $query_factory);
```

Hope that helps

**Comment by Fale** [comment]
Thanks :).
Does this makes sense? I mean, if the goal is to provide an empty ColumnFactory, wouldn't have more sense something like this?

```
/**
 * 
 * Constructor.
 * 
 * @param PDO $pdo A database connection.
 * 
 */
public function __construct(PDO $pdo)
{
    $this->pdo = $pdo;
    $this->column_factory = new ColumnFactory();
}
```

**Comment by pmjones** [comment]
@Fale It makes sense in a non-DI scenario, but we in Aura are strict DI adherents. We only new `new` in factory objects. ;-)

No, real solution here is to modify the documentation. If you want to send a PR for that, you will automatically get listed as a contributor.  Otherwise I or @harikt can edit the doc ourselves.

Thanks for finding this!

**Comment by harikt** [comment]
> No, real solution here is to modify the documentation. If you want to send
> a PR for that, you will automatically get listed as a contributor.
> Otherwise I or @harikt https://github.com/harikt can edit the doc
> ourselves.
> 
> Yes that's it. Feel free to send a PR in the docs.

**Comment by Fale** [comment]
Thanks for the explanation :). I have opened a pull request that fix the doc :)

**Comment by harikt** [comment]
@pmjones please close the issue.

**Comment by pmjones** [comment]
Oh, huh, I thought Github would do that automatically. Thanks.

**Comment by harikt** [comment]
@pmjones I would have not asked if I have the permission :D .
