### ISSUE TITLE
Fetch Microsoft SQL Server table by dot notation

### ISSUE THREAD

**Issue by crissi** [auraphp/Aura.SqlSchema#8]
Being able to fetch a table by dot notation.

I am using sqlsrv.

Sometimes my connection is set to use ex. table "global.dbo.some_table" and when it is set to this, which is perfectly valid, it unfortunately fails to retrieve the colums.

**Comment by pmjones** [comment]
We are woefully without a Microsoft SQL Server instance to test against. If you can provide a patch and a test that would help a great deal.

**Comment by pmjones** [comment]
Closing due to lack of feedback. @crissi if you can submit a PR and a test that provides this functionality, I'll be happy to review it.
